### ISSUE TITLE
a little help?

### ISSUE THREAD

**Issue by chrisbraddock** [kartsims/vue-cordova-demo#3]
Hey - I've implemented vue-cordova (thank-you!). I used this demo template as my dry run but I wanted an implementation that follows the [vue-templates webpack template](https://github.com/vuejs-templates/webpack) as minimally and as closely as possible. I've been trying to get there with [this](https://github.com/chrisbraddock/vue-templates-webpack-cordova) so far.

If you've got some bandwidth maybe you could field a few questions? I'm happy to contribute back to here if that ends up making sense.

**Comment by kartsims** [comment]
Hi Chris,
This is a great idea :+1: 
This demo has been made using Vue Webpack template a few days ago so we shouldn't be far

Just to let you know the main pain point with this demo was the integration of Cordova itself, that is why I ended up committing the `platforms` and `plugins` directories. I wish I could have done otherwise but someone reported an issue with it that I could reproduce on another computer so I chose the easy path by adding these files to the repo.

Now let's take some time here to discuss your issues I have unlimited bandwidth ;)

**Comment by chrisbraddock** [comment]
Wonderful - thank you again.

I didn't run in to an issue with those directories other than they had to exist in order for the project to be recognized as a Cordova project. I think I .gitkeep'ed them. I've tested following my instructions and starting with that project "from scratch" and I think it worked without me having to take additional steps so maybe that is an okay way to go. I can't say for sure yet. :) If anything I may have forgotten one of those or another directory that Cordova expects but otherwise I think it's okay.

As of now I'm deploying to both iOS and Android physical devices with success.

I do not have hot reload working. Honestly, I'm unfamiliar enough with mobile dev to not even understand if it should be working. :) I think I've seen other projects that claim it works and obviously it'd be great if it did - so to get that wrapped up one way or another would be my first want.

**Comment by kartsims** [comment]
The problem with hot reloading and Cordova is that you need to have an open socket and serve files and reload chunks of code through there so it means two things :
1. your app needs to be authorized to access an external URL (in the config.xml file of Cordova)
2. you need to have an endpoint reachable from within your Cordova app, which has to be on your local computer (otherwise hot reloading makes no sense) so the best solution for that is to set up an ngrok tunnel (or you can configure it on your local network manually to run offline)

I have seen this implemented in this example : https://github.com/nordnet/cordova-hot-code-push it is not trivial and uses ngrok (so doesn't work offline) but it works I tested it.

**Comment by kartsims** [comment]
I am no webpack expert but I guess if we could 

- use the `index.html` generated from `npm run dev`
- update the socket URL to use ngrok
- serve this file and whatever is needed in the `www` folder of Cordova

This would build an app based on the websocket. This is all theoretical but could work... I might give it a try sometime later if you don't/can't.

**Comment by kartsims** [comment]
So I looked into it a bit and couldn't get far as I don't have a deep knowledge of Webpack...

`npm run dev` uses [webpack-dev-middleware](https://github.com/webpack/webpack-dev-middleware) which does not write file to disk, but serves them via HTTP. 
It is designed this way, however we need to extract the original HTML to feed it to Cordova, while keeping the hot reload server in place.

I don't really know how to achieve this. If you are still working on this I suggest we move the discussion to your repo as it doesn't really concern this demo for vue-cordova, what do you think ?

**Comment by chrisbraddock** [comment]
After reading that Medium article response from Evan You and taking a new look at the WeeX timeline, Im not sure what to do. I may just try out Weex and see how functional it is. I see hot reloading is not far off on the roadmap so maybe this is too much effort for me for a temporary solution.

**Comment by kartsims** [comment]
Yes for sure, Weex is (or will be very soon) the way to go ;-)
